import {
  createTheme,
  type DefaultMantineColor,
  type MantineColorsTuple,
} from "@mantine/core";

// Generated by https://mantine.dev/colors-generator/?color=2f419b
// #2f419b is the blue color taken from the GO logo
const primary: MantineColorsTuple = [
  "#eef1ff",
  "#dbdff4",
  "#b4bce5",
  "#8a96d7",
  "#6777cb",
  "#5163c5",
  "#4559c2",
  "#3749ac",
  "#2f419b",
  "#243789",
];

// Generated by https://mantine.dev/colors-generator/?color=588fb7
// #588fb7 is the teal color taken from the GO logo
const secondary: MantineColorsTuple = [
  "#e8f7ff",
  "#dae9f4",
  "#b8d1e2",
  "#93b7d0",
  "#74a0c1",
  "#5f93b8",
  "#588fb7",
  "#4279a0",
  "#366b90",
  "#235d81",
];

type ExtendedCustomColors = "primary" | "secondary" | DefaultMantineColor;
declare module "@mantine/core" {
  export interface MantineThemeColorsOverride {
    colors: Record<ExtendedCustomColors, MantineColorsTuple>;
  }
}

const theme = createTheme({
  primaryColor: "primary",
  colors: {
    primary,
    secondary,
  },
});

export default theme;
